[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version='cancun'
via-ir = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@solady/=lib/solady/src/",
]