name: Unit Test Generation Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Remove all test files except OpixSlot.t.sol
        run: |
          find . -type f -name '*.t.sol' ! -name 'OpixSlot.t.sol' -exec rm {} +

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1

      - name: Install dependencies
        run: npm install
      
      - name: Unit Test Generator
        uses: olympix/test-generator@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
          OLYMPIX_GITHUB_ACCESS_TOKEN: ${{ secrets.OLYMPIX_GITHUB_ACCESS_TOKEN }}
